# Generated by Django 4.0.5 on 2022-06-18 19:40

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='business',
            name='establishment_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2022, 6, 18))]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='business_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_user', to='base.businessuser'),
        ),
    ]
